%% Fig2_RMS.m
% =========================================================================
% Calculate 30-minute RMS values from continuous, response-corrected
% acceleration SAC data and generate the RMS panels used in Figure 2.
%
% Expected repository layout:
%
% Test_SUSTech/
% ├── ESS_OBS_Shield_Data_v1.0/
% │   ├── Pro_Seismic_acceleration_v1.0/
% │   └── Raw_Current_Tide_v1.0/
% │       ├── dataforzzh.mat
% │       └── Tide_UTC.txt
% │
% └── ESS_OBS_Shield_Scripts_v1.0/
%     └── Fig2_RMS.m
%
% Outputs:
%   outputs/Processed_RMS_v1.0/Results_RMS.mat
%   outputs/Figure2/*.tif
%
% The RMS calculation and plotting logic are retained from the original
% analysis script. Only repository-relative paths and input checks were
% introduced for public release.
% =========================================================================

clc;
clear;
close all;

%% Repository-relative paths

script_file = mfilename('fullpath');

if isempty(script_file)
    error(['MATLAB cannot determine the location of Fig2_RMS.m. ', ...
           'Run the saved script file rather than an unsaved editor buffer.']);
end

script_root  = fileparts(script_file);
project_root = fileparts(script_root);

data_root = fullfile( ...
    project_root, ...
    'ESS_OBS_Shield_Data_v1.0');

rd4data = fullfile( ...
    data_root, ...
    'Pro_Seismic_acceleration_v1.0');

current_tide_dir = fullfile( ...
    data_root, ...
    'Raw_Current_Tide_v1.0');

current_mat_file = fullfile( ...
    current_tide_dir, ...
    'dataforzzh.mat');

tide_file = fullfile( ...
    current_tide_dir, ...
    'Tide_UTC.txt');

rms_output_dir = fullfile( ...
    script_root, ...
    'outputs', ...
    'Processed_RMS_v1.0');

figure_output_dir = fullfile( ...
    script_root, ...
    'outputs', ...
    'Figure2');

required_paths = {
    rd4data
    current_mat_file
    tide_file
};

for i_path = 1:numel(required_paths)
    this_path = required_paths{i_path};

    if ~(isfolder(this_path) || isfile(this_path))
        error('Required input not found: %s', this_path);
    end
end

if ~exist(rms_output_dir, 'dir')
    mkdir(rms_output_dir);
end

if ~exist(figure_output_dir, 'dir')
    mkdir(figure_output_dir);
end

%% Basic settings

stations = {'T01', 'T02'};
Fs_expected = 100;
winLen = 1800;

% RMS calculation range:
% Each value below is the start time of a 30 min RMS window.
calc_start_date = datenum(2025, 3, 14, 0, 0, 0);
calc_end_date   = datenum(2025, 3, 31, 23, 0, 0);

% Plotting/statistical-display range:
% Edge periods affected by the response-removal taper are excluded.
plot_start_date = datenum(2025, 3, 15, 0, 0, 0);
plot_end_date   = datenum(2025, 3, 30, 23, 0, 0);

if plot_start_date < calc_start_date || ...
   plot_end_date > calc_end_date

    error('The plotting range must lie inside the RMS calculation range.');
end

%% Current data

current_data = load(current_mat_file);

required_current_variables = {
    'rcm_time'
    'rcm_hor_vel_true'
};

for i_var = 1:numel(required_current_variables)
    variable_name = required_current_variables{i_var};

    if ~isfield(current_data, variable_name)
        error( ...
            'Required variable "%s" is absent from %s.', ...
            variable_name, ...
            current_mat_file);
    end
end

% Original MAT-file time is Beijing time; convert to UTC.
rcm_time = current_data.rcm_time(:) - 8 / 24;

% Original current speed is in cm/s; convert to m/s.
rcm_vel = current_data.rcm_hor_vel_true(:) / 100;

%% Tide data

opts = detectImportOptions( ...
    tide_file, ...
    'Delimiter', '\t');

opts.VariableNamesLine = 1;
opts.DataLines = [2 Inf];

tide_raw = readtable(tide_file, opts);

Time_Tide = datenum(datetime( ...
    tide_raw{:, 1}, ...
    'InputFormat', 'yyyy-MM-dd HH:mm:ss'));

Level_Tide = tide_raw{:, 2} / 100;

%% RMS calculation

Results = struct( ...
    'station', {}, ...
    'TIME', {}, ...
    'CURR', {}, ...
    'BH_RMS', {}, ...
    'BZ_RMS', {}, ...
    'BH_BZ', {});

window_step_day = winLen / 86400;
window_start_times = ...
    calc_start_date:window_step_day:calc_end_date;

nWin = numel(window_start_times);

for s = 1:numel(stations)

    sta = stations{s};
    fprintf('\nStation %s\n', sta);

    sacE = dir(fullfile( ...
        rd4data, ...
        sprintf('ZS.%s.LC.BHE*.SAC', sta)));

    sacN = dir(fullfile( ...
        rd4data, ...
        sprintf('ZS.%s.LC.BHN*.SAC', sta)));

    sacZ = dir(fullfile( ...
        rd4data, ...
        sprintf('ZS.%s.LC.BHZ*.SAC', sta)));

    if isempty(sacE) || isempty(sacN) || isempty(sacZ)
        warning('Station %s is missing one or more SAC components. Skipping.', sta);
        continue
    end

    if numel(sacE) > 1 || numel(sacN) > 1 || numel(sacZ) > 1
        warning([ ...
            'Station %s has multiple matching SAC files. ', ...
            'Only the first matching file for each component is used.'], ...
            sta);
    end

    fileE = fullfile(rd4data, sacE(1).name);
    fileN = fullfile(rd4data, sacN(1).name);
    fileZ = fullfile(rd4data, sacZ(1).name);

    [E, hdE] = rdSac_with_time(fileE);
    [N, hdN] = rdSac_with_time(fileN);
    [Z, hdZ] = rdSac_with_time(fileZ);

    %% Sampling-rate checks

    Fs = hdE.Fs;

    if abs(hdN.Fs - Fs) > 1e-6 || ...
       abs(hdZ.Fs - Fs) > 1e-6

        error( ...
            '%s: the sampling rates of the three components are inconsistent.', ...
            sta);
    end

    if abs(Fs - Fs_expected) > 1e-6
        warning( ...
            '%s: actual sampling rate is %.8f Hz, not %.8f Hz.', ...
            sta, ...
            Fs, ...
            Fs_expected);
    end

    samplesPerWin = round(winLen * Fs);

    fprintf( ...
        '  BHE: %s to %s, Fs = %.6f Hz\n', ...
        datestr(hdE.startTime, 'yyyy-mm-dd HH:MM:SS.FFF'), ...
        datestr(hdE.endTime,   'yyyy-mm-dd HH:MM:SS.FFF'), ...
        Fs);

    fprintf( ...
        '  BHN: %s to %s, Fs = %.6f Hz\n', ...
        datestr(hdN.startTime, 'yyyy-mm-dd HH:MM:SS.FFF'), ...
        datestr(hdN.endTime,   'yyyy-mm-dd HH:MM:SS.FFF'), ...
        Fs);

    fprintf( ...
        '  BHZ: %s to %s, Fs = %.6f Hz\n', ...
        datestr(hdZ.startTime, 'yyyy-mm-dd HH:MM:SS.FFF'), ...
        datestr(hdZ.endTime,   'yyyy-mm-dd HH:MM:SS.FFF'), ...
        Fs);

    %% Preallocate output arrays

    TIME   = window_start_times;
    CURR   = nan(1, nWin);
    BH_RMS = nan(1, nWin);
    BZ_RMS = nan(1, nWin);
    BH_BZ  = nan(1, nWin);

    for w = 1:nWin

        t0 = window_start_times(w);

        idxE1 = round( ...
            (t0 - hdE.startTime) * 86400 * Fs) + 1;

        idxN1 = round( ...
            (t0 - hdN.startTime) * 86400 * Fs) + 1;

        idxZ1 = round( ...
            (t0 - hdZ.startTime) * 86400 * Fs) + 1;

        idxE2 = idxE1 + samplesPerWin - 1;
        idxN2 = idxN1 + samplesPerWin - 1;
        idxZ2 = idxZ1 + samplesPerWin - 1;

        if idxE1 < 1 || idxN1 < 1 || idxZ1 < 1 || ...
           idxE2 > numel(E) || ...
           idxN2 > numel(N) || ...
           idxZ2 > numel(Z)

            warning( ...
                '%s: no complete three-component window at %s. Assigned NaN.', ...
                sta, ...
                datestr(t0, 'yyyy-mm-dd HH:MM:SS'));

            continue
        end

        E_win = double(E(idxE1:idxE2));
        N_win = double(N(idxN1:idxN2));
        Z_win = double(Z(idxZ1:idxZ2));

        valid = ...
            isfinite(E_win) & ...
            isfinite(N_win) & ...
            isfinite(Z_win);

        if mean(valid) < 0.99
            warning( ...
                '%s: valid-data fraction < 99%% at %s. Assigned NaN.', ...
                sta, ...
                datestr(t0, 'yyyy-mm-dd HH:MM:SS'));

            continue
        end

        % Linear detrending only; no Hann taper is applied before RMS.
        E_prep = detrend(E_win, 'linear');
        N_prep = detrend(N_win, 'linear');
        Z_prep = detrend(Z_win, 'linear');

        BH = sqrt(E_prep.^2 + N_prep.^2);

        BH_RMS(w) = rms(BH);
        BZ_RMS(w) = rms(Z_prep);
        BH_BZ(w)  = BH_RMS(w) / BZ_RMS(w);

        % Current speed is interpolated at the start time of each window.
        CURR(w) = interp1( ...
            rcm_time, ...
            rcm_vel, ...
            t0, ...
            'linear', ...
            NaN);
    end

    Results(s) = struct( ...
        'station', sta, ...
        'TIME', TIME, ...
        'CURR', CURR, ...
        'BH_RMS', BH_RMS, ...
        'BZ_RMS', BZ_RMS, ...
        'BH_BZ', BH_BZ);
end

save( ...
    fullfile(rms_output_dir, 'Results_RMS.mat'), ...
    'Results', ...
    'calc_start_date', ...
    'calc_end_date', ...
    'plot_start_date', ...
    'plot_end_date');

%% Plot Figure 2 RMS panels

plot_all_figures( ...
    Results, ...
    plot_start_date, ...
    plot_end_date, ...
    figure_output_dir, ...
    Time_Tide, ...
    Level_Tide);

fprintf('\nDone\n');

%% =========================================================================
% Local plotting and SAC-reading functions
% =========================================================================

function plot_all_figures( ...
    Results, ...
    plot_start_date, ...
    plot_end_date, ...
    figure_output_dir, ...
    Time_Tide, ...
    Level_Tide)

if numel(Results) < 2 || ...
   isempty(Results(1).TIME) || ...
   isempty(Results(2).TIME)

    error('Valid RMS results for both T01 and T02 are required.');
end

plotMask1 = ...
    Results(1).TIME >= plot_start_date & ...
    Results(1).TIME <= plot_end_date;

plotMask2 = ...
    Results(2).TIME >= plot_start_date & ...
    Results(2).TIME <= plot_end_date;

tideMask = ...
    Time_Tide >= plot_start_date & ...
    Time_Tide <= plot_end_date;

Common_YLim = get_log_ylim([ ...
    Results(1).BH_RMS(plotMask1), ...
    Results(2).BH_RMS(plotMask2), ...
    Results(1).BZ_RMS(plotMask1), ...
    Results(2).BZ_RMS(plotMask2)]);

%% Current speed versus horizontal RMS

valid1 = ...
    plotMask1 & ...
    isfinite(Results(1).CURR) & ...
    isfinite(Results(1).BH_RMS) & ...
    Results(1).BH_RMS > 0;

valid2 = ...
    plotMask2 & ...
    isfinite(Results(2).CURR) & ...
    isfinite(Results(2).BH_RMS) & ...
    Results(2).BH_RMS > 0;

fig = figure( ...
    'Visible', 'off', ...
    'Position', [100 100 800 400]);

hold on

scatter( ...
    Results(1).CURR(valid1), ...
    Results(1).BH_RMS(valid1), ...
    18, ...
    'filled', ...
    'MarkerFaceColor', 'k', ...
    'MarkerEdgeColor', 'k');

scatter( ...
    Results(2).CURR(valid2), ...
    Results(2).BH_RMS(valid2), ...
    18, ...
    'filled', ...
    'MarkerFaceColor', 'r', ...
    'MarkerEdgeColor', 'r');

xlabel( ...
    'Current Speed (m/s)', ...
    'FontSize', 20, ...
    'FontName', 'Times New Roman');

ax = gca;

set( ...
    ax, ...
    'YScale', 'log', ...
    'FontSize', 17, ...
    'FontName', 'Times New Roman');

ax.YLim = Common_YLim;
ax.XGrid = 'on';
ax.YGrid = 'on';
ax.GridLineStyle = '--';
ax.GridAlpha = 0.4;
ax.XMinorTick = 'off';
ax.YMinorTick = 'off';
ax.XMinorGrid = 'off';
ax.YMinorGrid = 'off';

box on

exportgraphics( ...
    fig, ...
    fullfile(figure_output_dir, 'Figure2_Current_RMS_BH.tif'), ...
    'Resolution', 300);

close(fig)

%% Current speed versus vertical RMS

valid1 = ...
    plotMask1 & ...
    isfinite(Results(1).CURR) & ...
    isfinite(Results(1).BZ_RMS) & ...
    Results(1).BZ_RMS > 0;

valid2 = ...
    plotMask2 & ...
    isfinite(Results(2).CURR) & ...
    isfinite(Results(2).BZ_RMS) & ...
    Results(2).BZ_RMS > 0;

fig = figure( ...
    'Visible', 'off', ...
    'Position', [100 100 800 400]);

hold on

scatter( ...
    Results(1).CURR(valid1), ...
    Results(1).BZ_RMS(valid1), ...
    18, ...
    'filled', ...
    'MarkerFaceColor', 'k', ...
    'MarkerEdgeColor', 'k');

scatter( ...
    Results(2).CURR(valid2), ...
    Results(2).BZ_RMS(valid2), ...
    18, ...
    'filled', ...
    'MarkerFaceColor', 'r', ...
    'MarkerEdgeColor', 'r');

xlabel( ...
    'Current Speed (m/s)', ...
    'FontSize', 20, ...
    'FontName', 'Times New Roman');

ax = gca;

set( ...
    ax, ...
    'YScale', 'log', ...
    'FontSize', 17, ...
    'FontName', 'Times New Roman');

ax.YLim = Common_YLim;
ax.XGrid = 'on';
ax.YGrid = 'on';
ax.GridLineStyle = '--';
ax.GridAlpha = 0.4;
ax.XMinorTick = 'off';
ax.YMinorTick = 'off';
ax.XMinorGrid = 'off';
ax.YMinorGrid = 'off';

box on

exportgraphics( ...
    fig, ...
    fullfile(figure_output_dir, 'Figure2_Current_RMS_BZ.tif'), ...
    'Resolution', 300);

close(fig)

%% Horizontal RMS time evolution

valid1 = ...
    plotMask1 & ...
    isfinite(Results(1).BH_RMS) & ...
    Results(1).BH_RMS > 0;

valid2 = ...
    plotMask2 & ...
    isfinite(Results(2).BH_RMS) & ...
    Results(2).BH_RMS > 0;

fig = figure( ...
    'Visible', 'off', ...
    'Position', [100 100 800 400]);

hold on

yyaxis left

h1 = scatter( ...
    Results(1).TIME(valid1), ...
    Results(1).BH_RMS(valid1), ...
    18, ...
    'filled', ...
    'MarkerFaceColor', 'k', ...
    'MarkerEdgeColor', 'k');

h2 = scatter( ...
    Results(2).TIME(valid2), ...
    Results(2).BH_RMS(valid2), ...
    18, ...
    'filled', ...
    'MarkerFaceColor', 'r', ...
    'MarkerEdgeColor', 'r');

xlim([plot_start_date plot_end_date])
xticks(plot_start_date:3:plot_end_date);
datetick('x', 'mmm.dd', 'keepticks')

ax = gca;
ax.YColor = 'k';

set( ...
    ax, ...
    'YScale', 'log', ...
    'FontSize', 17, ...
    'FontName', 'Times New Roman');

ax.YLim = Common_YLim;
ax.XGrid = 'on';
ax.YGrid = 'on';
ax.GridLineStyle = '--';
ax.GridAlpha = 0.4;
ax.XMinorTick = 'off';
ax.YMinorTick = 'off';
ax.XMinorGrid = 'off';
ax.YMinorGrid = 'off';

box on

yyaxis right

h3 = plot( ...
    Time_Tide(tideMask), ...
    Level_Tide(tideMask), ...
    '-', ...
    'Color', [0.5 0.5 0.5], ...
    'LineWidth', 1.0);

ylabel( ...
    'Tide level (m)', ...
    'Color', 'k', ...
    'FontSize', 20, ...
    'FontName', 'Times New Roman');

ax = gca;
ax.YColor = [0.5 0.5 0.5];
ax.YTick = 1:1:4;
ax.YLim = [0 4.2];

lgd = legend( ...
    [h1, h2, h3], ...
    {'T01', 'T02', 'Tide level'}, ...
    'Location', 'north', ...
    'NumColumns', 3, ...
    'Orientation', 'horizontal', ...
    'Box', 'on', ...
    'FontSize', 13, ...
    'FontName', 'Times New Roman');

lgd.ItemTokenSize = [10, 6];

exportgraphics( ...
    fig, ...
    fullfile(figure_output_dir, 'Figure2_TimeEvolution_RMS_BH.tif'), ...
    'Resolution', 300);

close(fig)

%% Vertical RMS time evolution

valid1 = ...
    plotMask1 & ...
    isfinite(Results(1).BZ_RMS) & ...
    Results(1).BZ_RMS > 0;

valid2 = ...
    plotMask2 & ...
    isfinite(Results(2).BZ_RMS) & ...
    Results(2).BZ_RMS > 0;

fig = figure( ...
    'Visible', 'off', ...
    'Position', [100 100 800 400]);

hold on

yyaxis left

scatter( ...
    Results(1).TIME(valid1), ...
    Results(1).BZ_RMS(valid1), ...
    18, ...
    'filled', ...
    'MarkerFaceColor', 'k', ...
    'MarkerEdgeColor', 'k');

scatter( ...
    Results(2).TIME(valid2), ...
    Results(2).BZ_RMS(valid2), ...
    18, ...
    'filled', ...
    'MarkerFaceColor', 'r', ...
    'MarkerEdgeColor', 'r');

xlim([plot_start_date plot_end_date])
xticks(plot_start_date:3:plot_end_date);
datetick('x', 'mmm.dd', 'keepticks')

ax = gca;
ax.YColor = 'k';

set( ...
    ax, ...
    'YScale', 'log', ...
    'FontSize', 17, ...
    'FontName', 'Times New Roman');

ax.YLim = Common_YLim;
ax.XGrid = 'on';
ax.YGrid = 'on';
ax.GridLineStyle = '--';
ax.GridAlpha = 0.4;
ax.XMinorTick = 'off';
ax.YMinorTick = 'off';
ax.XMinorGrid = 'off';
ax.YMinorGrid = 'off';

box on

yyaxis right

plot( ...
    Time_Tide(tideMask), ...
    Level_Tide(tideMask), ...
    '-', ...
    'Color', [0.5 0.5 0.5], ...
    'LineWidth', 1.0);

ylabel( ...
    'Tide level (m)', ...
    'Color', [0.5 0.5 0.5], ...
    'FontSize', 20, ...
    'FontName', 'Times New Roman');

ax = gca;
ax.YColor = 'k';
ax.YLim = [0 4.2];
ax.YTick = 1:1:4;

exportgraphics( ...
    fig, ...
    fullfile(figure_output_dir, 'Figure2_TimeEvolution_RMS_BZ.tif'), ...
    'Resolution', 300);

close(fig)
end

function [data, hd] = rdSac_with_time(sacFile)

[data, hd, ok] = read_sac_endian(sacFile, 'ieee-le');

if ~ok
    [data, hd, ok] = read_sac_endian(sacFile, 'ieee-be');
end

if ~ok
    error( ...
        'Unable to determine SAC byte order or invalid SAC header: %s', ...
        sacFile);
end
end

function [data, hd, ok] = read_sac_endian(sacFile, machineFormat)

data = [];
hd = struct();
ok = false;

fid = fopen(sacFile, 'r', machineFormat);

if fid < 0
    error('Cannot open SAC file: %s', sacFile);
end

floatHeader = fread(fid, 70, 'single=>double');
intHeader   = fread(fid, 40, 'int32=>double');
charHeader  = fread(fid, 192, 'uint8=>uint8');
data        = fread(fid, inf, 'single=>single');

fclose(fid);

if numel(floatHeader) ~= 70 || ...
   numel(intHeader) ~= 40 || ...
   numel(charHeader) ~= 192

    return
end

delta  = floatHeader(1);
b      = floatHeader(6);

nzyear = intHeader(1);
nzjday = intHeader(2);
nzhour = intHeader(3);
nzmin  = intHeader(4);
nzsec  = intHeader(5);
nzmsec = intHeader(6);
npts   = intHeader(10);

if ~(isfinite(delta) && delta > 0 && delta < 100) || ...
   ~(nzyear >= 1900 && nzyear <= 2100) || ...
   ~(nzjday >= 1 && nzjday <= 366) || ...
   ~(nzhour >= 0 && nzhour <= 23) || ...
   ~(nzmin >= 0 && nzmin <= 59) || ...
   ~(nzsec >= 0 && nzsec <= 60) || ...
   ~(nzmsec >= 0 && nzmsec <= 999) || ...
   ~(npts > 0)

    return
end

if npts ~= numel(data)
    warning([ ...
        'SAC header NPTS (%d) differs from the number of samples ', ...
        'read from file (%d): %s'], ...
        npts, ...
        numel(data), ...
        sacFile);
end

referenceTime = datenum( ...
    nzyear, ...
    1, ...
    1, ...
    nzhour, ...
    nzmin, ...
    nzsec + nzmsec / 1000);

startTime = referenceTime + ...
    (nzjday - 1) + ...
    b / 86400;

Fs = 1 / delta;

endTime = startTime + ...
    (numel(data) - 1) / (Fs * 86400);

hd.delta = delta;
hd.Fs = Fs;
hd.b = b;
hd.npts = npts;
hd.startTime = startTime;
hd.endTime = endTime;
hd.machineFormat = machineFormat;
hd.floatHeader = floatHeader;
hd.intHeader = intHeader;

ok = true;
end

function yLim = get_log_ylim(ydata)

ydata = ydata(isfinite(ydata) & ydata > 0);

if isempty(ydata)
    error('No positive finite RMS values are available for Y-axis limits.');
end

lowerExp = floor(2 * log10(min(ydata))) / 2;
upperExp = ceil(2 * log10(max(ydata))) / 2;

if upperExp <= lowerExp
    upperExp = lowerExp + 0.5;
end

yLim = 10 .^ [lowerExp, upperExp];
end
