%% Fig3_PSD_PSDDiff.m
% =========================================================================
% Generate the PSD and PSD-difference panels used in Figure 3.
%
% Left panel:
%   Whole-period PSD median and IQR for T01, T02, and ZSD02.
%
% Right panel:
%   PSDdiff = PSD(T02) - PSD(T01), plotted as median, IQR, min-max range,
%   and the zero reference line.
%
% Expected repository layout:
%
% Test_SUSTech/
% ├── ESS_OBS_Shield_Data_v1.0/
% │   └── Processed_PSD_v1.0/
% │
% └── ESS_OBS_Shield_Scripts_v1.0/
%     └── Fig3_PSD_PSDDiff.m
%
% Outputs:
%   outputs/Figure3/
%
% The PSD statistics, PSDdiff calculation, noise models, and plotting
% settings are retained from the original script. Only relative paths,
% public-release filenames, and required-input checks were introduced.
% =========================================================================

clc;
clear;
close all;

%% Repository-relative paths

script_file = mfilename('fullpath');

if isempty(script_file)
    error(['MATLAB cannot determine the location of Fig3_PSD_PSDDiff.m. ', ...
           'Run the saved script file rather than an unsaved editor buffer.']);
end

script_root  = fileparts(script_file);
project_root = fileparts(script_root);

data_root = fullfile( ...
    project_root, ...
    'ESS_OBS_Shield_Data_v1.0');

rd4PSD = fullfile( ...
    data_root, ...
    'Processed_PSD_v1.0');

rd4RESULT = fullfile( ...
    script_root, ...
    'outputs', ...
    'Figure3');

if ~isfolder(rd4PSD)
    error('Processed PSD directory not found: %s', rd4PSD);
end

if ~exist(rd4RESULT, 'dir')
    mkdir(rd4RESULT);
end

stations = {'T01', 'T02', 'ZSD02'};
Comps = {'BHE', 'BHN', 'BHZ'};

st_1 = '20250314';
et_1 = '20250331';

%% Plot settings

color_T01 = [0.0000 0.4470 0.7410];
color_T02 = [0.8500 0.3250 0.0980];
color_ZSD = [0.4660 0.6740 0.1880];

median_lw = 2.5;
noise_lw = 1.5;
face_alpha = 0.30;

%% Noise models: NLNM and NHNM

PL = [ ...
    0.10 0.17 0.40 0.80 1.24 2.40 4.30 5.00 6.00 10.00 ...
    12.00 15.60 21.90 31.60 45.00 70.00 101.00 154.00 ...
    328.00 600.00 10000.00 100000.00];

AL = [ ...
    -162.36 -166.70 -170.00 -166.40 -168.60 -159.98 ...
    -141.10 -72.36 -97.26 -132.18 -205.27 -37.65 ...
    -114.37 -160.58 -187.50 -216.47 -185.00 -168.34 ...
    -217.43 -258.28 -346.88 -346.88];

BL = [ ...
    5.64 0.00 -8.30 28.90 52.48 29.81 0.00 -99.77 ...
    -66.49 -31.57 36.16 -104.33 -47.10 -16.28 0.00 ...
    15.70 0.00 -7.61 11.90 26.60 48.75 48.75];

PH = [ ...
    0.10 0.22 0.32 0.80 3.80 4.60 6.30 7.90 ...
    15.40 20.00 345.80 100000.00];

AH = [ ...
    -108.73 -150.34 -122.31 -116.85 -108.48 -74.66 ...
    0.66 -93.37 73.54 -151.52 -206.66 -206.66];

BH = [ ...
    -17.23 -80.50 -23.87 32.51 18.08 -32.95 ...
    -127.18 -22.42 -162.98 10.01 34.63 31.63];

NLNM = zeros(size(PL));
fL = zeros(size(PL));

for i = 1:length(PL)
    NLNM(i) = AL(i) + BL(i) * log10(PL(i));
    fL(i) = 1 / PL(i);
end

NHNM = zeros(size(PH));
fH = zeros(size(PH));

for i = 1:length(PH)
    NHNM(i) = AH(i) + BH(i) * log10(PH(i));
    fH(i) = 1 / PH(i);
end

%% Main component loop

for c = 1:numel(Comps)

    comp = Comps{c};
    fprintf('\nProcessing component: %s\n', comp);

    PSDstat = struct();

    %% Left-panel PSD statistics

    for s = 1:numel(stations)

        station = stations{s};

        switch station
            case 'T01'
                mainColor = color_T01;
                comp_use = comp;

            case 'T02'
                mainColor = color_T02;
                comp_use = comp;

            case 'ZSD02'
                mainColor = color_ZSD;
                comp_use = strrep(comp, 'BH', 'HH');

            otherwise
                error('Unsupported station: %s', station);
        end

        p_name = fullfile( ...
            rd4PSD, ...
            sprintf( ...
            'PSD_%s_%s_%s_%s.PSD', ...
            station, ...
            comp_use, ...
            st_1, ...
            et_1));

        fprintf('Reading: %s\n', p_name);

        if ~isfile(p_name)
            warning('Missing PSD file: %s', p_name);
            continue
        end

        P_data = load(p_name);

        F_ref = P_data(2:end, 1);
        PP = P_data(2:end, 2:end);

        valid_cols = ~all(isnan(PP), 1);
        PP = PP(:, valid_cols);

        if isempty(PP)
            warning('No valid hourly PSD columns found in %s', p_name);
            continue
        end

        PSDstat.(station).F = F_ref;
        PSDstat.(station).PP = PP;
        PSDstat.(station).median = median(PP, 2, 'omitnan');
        PSDstat.(station).p25 = prctile(PP', 25)';
        PSDstat.(station).p75 = prctile(PP', 75)';
        PSDstat.(station).color = mainColor;
    end

    %% Right-panel PSDdiff statistics

    file1 = fullfile( ...
        rd4PSD, ...
        sprintf( ...
        'PSD_T01_%s_%s_%s.PSD', ...
        comp, ...
        st_1, ...
        et_1));

    file2 = fullfile( ...
        rd4PSD, ...
        sprintf( ...
        'PSD_T02_%s_%s_%s.PSD', ...
        comp, ...
        st_1, ...
        et_1));

    if ~(isfile(file1) && isfile(file2))
        warning( ...
            'T01/T02 PSD files are missing for component %s. Skipping.', ...
            comp);
        continue
    end

    Pdata1 = load(file1);
    Pdata2 = load(file2);

    F_diff_full = Pdata1(2:end, 1);
    PSD1 = Pdata1(2:end, 2:end);
    PSD2 = Pdata2(2:end, 2:end);

    ncol = min(size(PSD1, 2), size(PSD2, 2));

    PSD1 = PSD1(:, 1:ncol);
    PSD2 = PSD2(:, 1:ncol);

    valid_pair = ...
        ~(all(isnan(PSD1), 1) | all(isnan(PSD2), 1));

    PSD1 = PSD1(:, valid_pair);
    PSD2 = PSD2(:, valid_pair);

    if isempty(PSD1) || isempty(PSD2)
        warning('No paired PSD columns found for component %s. Skipping.', comp);
        continue
    end

    PSDdiff = PSD2 - PSD1;

    medianPSD = median(PSDdiff, 2, 'omitnan');
    Q1 = prctile(PSDdiff, 25, 2);
    Q3 = prctile(PSDdiff, 75, 2);
    minPSD = min(PSDdiff, [], 2, 'omitnan');
    maxPSD = max(PSDdiff, [], 2, 'omitnan');

    valid_count = sum(~isnan(PSDdiff), 2);
    reduce_count = sum(PSDdiff < 0, 2, 'omitnan');
    reduce_prob = 100 * reduce_count ./ valid_count;
    reduce_prob(valid_count == 0) = NaN;

    step = 1;
    idx = 1:step:length(F_diff_full);

    Fp_diff = F_diff_full(idx);
    medianP = medianPSD(idx);
    Q1p = Q1(idx);
    Q3p = Q3(idx);
    minP = minPSD(idx);
    maxP = maxPSD(idx);
    ProbReduce = reduce_prob(idx);

    %% Figure 3

    fig = figure('Visible', 'off');

    set( ...
        fig, ...
        'Color', 'w', ...
        'Position', [100 100 1800 460]);

    tl = tiledlayout( ...
        1, ...
        2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    %% Left panel

    ax1 = nexttile(tl, 1);
    hold(ax1, 'on');

    order_left = {'T01', 'T02', 'ZSD02'};
    hMedian = gobjects(numel(order_left), 1);

    for k = 1:numel(order_left)

        station_name = order_left{k};

        if ~isfield(PSDstat, station_name)
            continue
        end

        F_left = PSDstat.(station_name).F;
        p25 = PSDstat.(station_name).p25;
        p75 = PSDstat.(station_name).p75;
        line_color = PSDstat.(station_name).color;

        x_patch = [F_left; flipud(F_left)];
        y_patch = [p25; flipud(p75)];

        patch( ...
            ax1, ...
            x_patch, ...
            y_patch, ...
            line_color, ...
            'FaceAlpha', face_alpha, ...
            'EdgeColor', 'none', ...
            'HandleVisibility', 'off');
    end

    semilogx( ...
        ax1, ...
        fL, ...
        NLNM, ...
        '--', ...
        'Color', [0.2 0.2 0.2], ...
        'LineWidth', noise_lw, ...
        'HandleVisibility', 'off');

    semilogx( ...
        ax1, ...
        fH, ...
        NHNM, ...
        '--', ...
        'Color', [0.2 0.2 0.2], ...
        'LineWidth', noise_lw, ...
        'HandleVisibility', 'off');

    text( ...
        ax1, ...
        0.012, ...
        -124, ...
        'NHNM', ...
        'FontSize', 17, ...
        'Color', [0.2 0.2 0.2], ...
        'FontAngle', 'italic', ...
        'FontName', 'Times New Roman');

    text( ...
        ax1, ...
        0.012, ...
        -180, ...
        'NLNM', ...
        'FontSize', 17, ...
        'Color', [0.2 0.2 0.2], ...
        'FontAngle', 'italic', ...
        'FontName', 'Times New Roman');

    for k = 1:numel(order_left)

        station_name = order_left{k};

        if ~isfield(PSDstat, station_name)
            continue
        end

        F_mean = PSDstat.(station_name).F;
        median_curve = PSDstat.(station_name).median;
        line_color = PSDstat.(station_name).color;

        hMedian(k) = semilogx( ...
            ax1, ...
            F_mean, ...
            median_curve, ...
            '-', ...
            'Color', line_color, ...
            'LineWidth', median_lw, ...
            'DisplayName', station_name);
    end

    for k = 1:numel(hMedian)
        if isgraphics(hMedian(k))
            uistack(hMedian(k), 'top');
        end
    end

    set( ...
        ax1, ...
        'XScale', 'log', ...
        'XLim', [0.01 40], ...
        'YLim', [-190 -60], ...
        'XTick', [0.01 0.05 0.1 0.5 1 5 10 40], ...
        'XTickLabel', { ...
        '0.01', '0.05', '0.1', '0.5', '1', '5', '10', '40'}, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 17, ...
        'LineWidth', 1.2, ...
        'TickDir', 'in', ...
        'Box', 'on', ...
        'Layer', 'top', ...
        'XMinorTick', 'on', ...
        'YMinorTick', 'on');

    grid(ax1, 'on');
    ax1.GridAlpha = 0.12;
    ax1.MinorGridAlpha = 0.08;

    xlabel( ...
        ax1, ...
        'Frequency (Hz)', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 20);

    ylabel( ...
        ax1, ...
        'PSD 10log_{10}(m/s^2)^2/Hz dB', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 20);

    valid_idx = isgraphics(hMedian);
    valid_handles = hMedian(valid_idx);
    valid_names = order_left(valid_idx);

    if strcmp(comp, 'BHZ')
        legend( ...
            ax1, ...
            valid_handles, ...
            valid_names, ...
            'Location', 'northeast', ...
            'Box', 'off', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 13);
    end

    %% Right panel

    ax2 = nexttile(tl, 2);
    hold(ax2, 'on');

    step_err = 2;
    idx_err = 1:step_err:length(Fp_diff);

    lowerErr = medianP(idx_err) - minP(idx_err);
    upperErr = maxP(idx_err) - medianP(idx_err);

    errorbar( ...
        ax2, ...
        Fp_diff(idx_err), ...
        medianP(idx_err), ...
        lowerErr, ...
        upperErr, ...
        'LineStyle', 'none', ...
        'Color', [0.7 0.7 0.7], ...
        'LineWidth', 0.9, ...
        'CapSize', 3, ...
        'DisplayName', 'Min–max range');

    x_patch2 = [Fp_diff; flipud(Fp_diff)];
    y_patch2 = [Q1p; flipud(Q3p)];

    patch( ...
        ax2, ...
        x_patch2, ...
        y_patch2, ...
        [0.55 0.55 0.55], ...
        'FaceAlpha', 0.45, ...
        'EdgeColor', 'none', ...
        'DisplayName', 'IQR (25%–75%)');

    yline( ...
        ax2, ...
        0, ...
        '-', ...
        'Color', [0.55 0.55 0.55], ...
        'LineWidth', 1.0, ...
        'HandleVisibility', 'off');

    h_median_diff = semilogx( ...
        ax2, ...
        Fp_diff, ...
        medianP, ...
        '-', ...
        'Color', [0.80 0.05 0.05], ...
        'LineWidth', median_lw, ...
        'DisplayName', 'Median PSDdiff');

    if strcmp(comp, 'BHZ')
        legend( ...
            ax2, ...
            h_median_diff, ...
            {'Median PSDdiff'}, ...
            'Location', 'northeast', ...
            'Box', 'off', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 13);
    end

    set( ...
        ax2, ...
        'XScale', 'log', ...
        'XLim', [0.01 40], ...
        'XTick', [0.01 0.05 0.1 0.2 0.5 1 5 10 40], ...
        'XTickLabel', { ...
        '0.01', '0.05', '0.1', '0.2', '0.5', '1', '5', '10', '40'}, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 17, ...
        'LineWidth', 1.2, ...
        'TickDir', 'in', ...
        'Box', 'on', ...
        'Layer', 'top', ...
        'XMinorTick', 'off', ...
        'YMinorTick', 'off');

    switch comp
        case {'BHE', 'BHN'}
            ylim(ax2, [-50 30]);
            yticks(ax2, -40:10:20);

        case 'BHZ'
            ylim(ax2, [-90 50]);
            yticks(ax2, -80:20:40);
    end

    grid(ax2, 'on');
    ax2.GridAlpha = 0.12;
    ax2.MinorGridAlpha = 0.08;

    xlabel( ...
        ax2, ...
        'Frequency (Hz)', ...
        'FontSize', 20, ...
        'FontName', 'Times New Roman');

    ylabel( ...
        ax2, ...
        'PSD Difference (dB)', ...
        'FontSize', 20, ...
        'FontName', 'Times New Roman');

    set(ax1, 'Position', [0.07 0.16 0.40 0.76]);
    set(ax2, 'Position', [0.56 0.16 0.40 0.76]);

    output_file = fullfile( ...
        rd4RESULT, ...
        sprintf('Figure3_%s.tiff', comp));

    exportgraphics( ...
        fig, ...
        output_file, ...
        'Resolution', 600);

    close(fig);

    %% Reduction-probability figure

    have_reduction = true;

    if have_reduction

        fig_prob = figure('Visible', 'off');

        set( ...
            fig_prob, ...
            'Color', 'w', ...
            'Position', [100 100 800 300]);

        hold on

        semilogx( ...
            Fp_diff, ...
            ProbReduce, ...
            '-', ...
            'Color', 'r', ...
            'LineWidth', 2.0);

        set( ...
            gca, ...
            'XScale', 'log', ...
            'XLim', [0.01 40], ...
            'YLim', [0 100], ...
            'XTick', [0.05 0.1 0.5 1 5 10 40], ...
            'XTickLabel', { ...
            '0.05', '0.1', '0.5', '1', '5', '10', '40'}, ...
            'YTick', 0:20:100, ...
            'FontName', 'Times New Roman', ...
            'FontSize', 10, ...
            'LineWidth', 1.0, ...
            'TickDir', 'in', ...
            'TickLength', [0.018 0.018], ...
            'Box', 'on', ...
            'Layer', 'top', ...
            'XMinorTick', 'on', ...
            'YMinorTick', 'on');

        grid on

        axp = gca;
        axp.GridAlpha = 0.10;
        axp.MinorGridAlpha = 0.05;
        axp.GridLineStyle = '-';
        axp.MinorGridLineStyle = '-';

        xlabel( ...
            'Frequency (Hz)', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12);

        ylabel( ...
            'Reduction probability (%)', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12);

        probability_file = fullfile( ...
            rd4RESULT, ...
            sprintf( ...
            'Figure3_ReductionProbability_%s.tiff', ...
            comp));

        exportgraphics( ...
            fig_prob, ...
            probability_file, ...
            'Resolution', 600);

        close(fig_prob);

        fprintf( ...
            'Saved reduction probability: %s\n', ...
            probability_file);
    end
end

disp('Finished.');
