%% Fig4_PSDDiff_CurrentSpeed.m
% =========================================================================
% Plot PSD difference as a function of current speed during flood and ebb
% tidal stages.
%
% PSDdiff = PSD_T02 - PSD_T01
%
% Negative PSDdiff indicates lower spectral power at the shielded OBS T02
% than at the unshielded OBS T01.
%
% This public version preserves the original scientific workflow:
%   1. Read hourly PSDdiff matrices;
%   2. Interpolate surface-current speed to the PSD time axis;
%   3. Classify each hourly PSD window as flood or ebb;
%   4. Extract frequency-time samples in three prescribed bands;
%   5. Bin samples by current speed;
%   6. Calculate and plot the median and interquartile range in each bin;
%   7. Save the plotted statistics.
%
% Changes made for public release:
%   - absolute paths replaced by repository-relative paths;
%   - output filenames corrected to Figure 4;
%   - duplicate calls to the same binning/plotting function removed;
%   - required-input checks added.
%
% Expected repository layout:
%
% Test_SUSTech/
% ├── ESS_OBS_Shield_Data_v1.0/
% │   ├── Processed_PSDDiff_v1.0/
% │   │   ├── DiffPSD_BHE_20250314_20250331.PSD
% │   │   ├── DiffPSD_BHN_20250314_20250331.PSD
% │   │   └── DiffPSD_BHZ_20250314_20250331.PSD
% │   └── Raw_Current_Tide_v1.0/
% │       ├── Flow_Speed_UTC.txt
% │       ├── FloodEvents.txt
% │       └── EbbEvents.txt
% │
% └── ESS_OBS_Shield_Scripts_v1.0/
%     └── Fig4_PSDDiff_CurrentSpeed.m
%
% IMPORTANT:
% FloodEvents.txt and EbbEvents.txt are required by the original workflow.
% They must be included in the public data package, or the two relative
% paths below must be changed to their actual public locations.
% =========================================================================

clc;
clear;
close all;

%% 1. Repository-relative paths

script_file = mfilename('fullpath');

if isempty(script_file)
    error(['MATLAB cannot determine the script location. ', ...
           'Run this saved script file rather than an unsaved editor buffer.']);
end

script_root  = fileparts(script_file);
project_root = fileparts(script_root);

data_root = fullfile( ...
    project_root, ...
    'ESS_OBS_Shield_Data_v1.0');

rd4PSDdiff = fullfile( ...
    data_root, ...
    'Processed_PSDDiff_v1.0');

rd4Curr = fullfile( ...
    data_root, ...
    'Raw_Current_Tide_v1.0');

speed_file = fullfile( ...
    rd4Curr, ...
    'Flow_Speed_UTC.txt');

floodFile = fullfile( ...
    rd4Curr, ...
    'FloodEvents.txt');

ebbFile = fullfile( ...
    rd4Curr, ...
    'EbbEvents.txt');

rd4Out = fullfile( ...
    script_root, ...
    'outputs', ...
    'Figure4');

if ~isfolder(rd4PSDdiff)
    error('PSDDiff directory not found: %s', rd4PSDdiff);
end

if ~isfolder(rd4Curr)
    error('Current/tide directory not found: %s', rd4Curr);
end

required_files = {
    speed_file
    floodFile
    ebbFile
};

for i_file = 1:numel(required_files)
    if ~isfile(required_files{i_file})
        error('Required input file not found: %s', required_files{i_file});
    end
end

if ~exist(rd4Out, 'dir')
    mkdir(rd4Out);
end

%% 2. Components and analysis period

Comps = {'BHE', 'BHN', 'BHZ'};

st = '20250314';
et = '20250331';

%% 3. Frequency bands

Bands = {
    '0.01–0.1 Hz', 0.01, 0.1;
    '0.1–10 Hz',   0.1,  10;
    '10–40 Hz',    10,   40
};

nBand = size(Bands, 1);

%% 4. Current-speed binning parameters

speed_bin_width = 0.05;
minN = 30;

%% 5. Plot settings

% These variables are retained from the original script for traceability.
marker_size  = 3; %#ok<NASGU>
marker_alpha = 0.15; %#ok<NASGU>

col_flood = [0.90 0.45 0.05];
col_ebb   = [0.45 0.25 0.65];

line_width  = 2.0;
shade_alpha = 0.20;

maxScatterPoints = 10000; %#ok<NASGU>

%% 6. Read current-speed observations

opts = detectImportOptions( ...
    speed_file, ...
    'Delimiter', '\t');

opts.VariableNamesLine = 1;
opts.DataLines = [2 Inf];

flow_raw = readtable(speed_file, opts);

Time_Flow_dt = datetime( ...
    flow_raw{:, 1}, ...
    'InputFormat', 'yyyy-MM-dd HH:mm:ss');

Time_Flow  = datenum(Time_Flow_dt);
Speed_Flow = flow_raw{:, 2};

[Time_Flow, ia] = unique(Time_Flow);
Speed_Flow = Speed_Flow(ia);

%% 7. Read flood and ebb event periods

[FloodStart, FloodEnd] = read_tidal_events(floodFile);
[EbbStart, EbbEnd]     = read_tidal_events(ebbFile);

%% 8. Main component loop

for c = 1:length(Comps)

    comp = Comps{c};

    PSDdiff_file = fullfile( ...
        rd4PSDdiff, ...
        sprintf( ...
        'DiffPSD_%s_%s_%s.PSD', ...
        comp, st, et));

    if ~isfile(PSDdiff_file)
        warning('PSDDiff file not found: %s', PSDdiff_file);
        continue
    end

    fprintf('Processing %s\n', PSDdiff_file);

    switch comp
        case {'BHE', 'BHN', 'BHZ'}
            y_lims  = [-45 25];
            y_ticks = -40:10:20;

        otherwise
            y_lims  = [-40 20];
            y_ticks = -40:10:20;
    end

    %% 8.1 Read PSDdiff matrix

    PSD = importdata(PSDdiff_file);

    PSD_time = PSD(1, 2:end);
    PSD_freq = PSD(2:end, 1);
    PSDdiff  = PSD(2:end, 2:end);

    %% 8.2 Interpolate current speed to the PSD time axis

    Speed_psd = interp1( ...
        Time_Flow, ...
        Speed_Flow, ...
        PSD_time, ...
        'linear', ...
        NaN);

    %% 8.3 Classify flood and ebb periods

    isFlood = in_periods( ...
        PSD_time, ...
        FloodStart, ...
        FloodEnd);

    isEbb = in_periods( ...
        PSD_time, ...
        EbbStart, ...
        EbbEnd);

    isValidStage = isFlood | isEbb;

    maxSpeed = max( ...
        Speed_psd(isValidStage), ...
        [], ...
        'omitnan');

    if isempty(maxSpeed) || isnan(maxSpeed)
        warning('No valid current speed found for %s.', comp);
        continue
    end

    speed_edges = 0:speed_bin_width: ...
        (ceil(maxSpeed / speed_bin_width) * ...
        speed_bin_width + speed_bin_width);

    speed_centers = ...
        (speed_edges(1:end-1) + speed_edges(2:end)) / 2;

    %% 8.4 Create Figure 4

    Fig = figure( ...
        'Visible', 'off', ...
        'Color', 'w', ...
        'Position', [100 100 1600 430]);

    Stats = struct();

    left0  = 0.070;
    bottom = 0.16;
    axW    = 0.285;
    axH    = 0.76;
    gap    = 0.02;

    for b = 1:nBand

        ax = axes( ...
            Fig, ...
            'Position', [ ...
            left0 + (b - 1) * (axW + gap), ...
            bottom, ...
            axW, ...
            axH]);

        hold(ax, 'on');

        f1 = Bands{b, 2};
        f2 = Bands{b, 3};

        [xFlood, yFlood] = extract_freqtime_samples( ...
            PSD_freq, ...
            PSDdiff, ...
            Speed_psd, ...
            isFlood, ...
            f1, ...
            f2);

        [xEbb, yEbb] = extract_freqtime_samples( ...
            PSD_freq, ...
            PSDdiff, ...
            Speed_psd, ...
            isEbb, ...
            f1, ...
            f2);

        % Each stage is calculated and plotted once.
        Stats(b).Flood = plot_binned_median_iqr_xy( ...
            ax, ...
            xFlood, ...
            yFlood, ...
            speed_edges, ...
            col_flood, ...
            minN, ...
            line_width, ...
            shade_alpha);

        Stats(b).Ebb = plot_binned_median_iqr_xy( ...
            ax, ...
            xEbb, ...
            yEbb, ...
            speed_edges, ...
            col_ebb, ...
            minN, ...
            line_width, ...
            shade_alpha);

        Stats(b).BandName = Bands{b, 1};
        Stats(b).f1 = f1;
        Stats(b).f2 = f2;

        yline( ...
            ax, ...
            0, ...
            '--k', ...
            'LineWidth', 1.0, ...
            'HandleVisibility', 'off');

        set( ...
            ax, ...
            'XLim', [0 0.8], ...
            'YLim', y_lims, ...
            'XTick', 0:0.1:0.7, ...
            'YTick', y_ticks, ...
            'FontName', 'Times New Roman', ...
            'FontSize', 15, ...
            'LineWidth', 1.2, ...
            'TickDir', 'in', ...
            'TickLength', [0.018 0.018], ...
            'Box', 'on', ...
            'Layer', 'top', ...
            'XMinorTick', 'on', ...
            'YMinorTick', 'off', ...
            'XColor', 'k', ...
            'YColor', 'k');

        try
            ax.XAxis.MinorTickValues = 0:0.1:0.8;
        catch
        end

        grid(ax, 'on');
        ax.GridAlpha = 0.12;
        ax.MinorGridAlpha = 0.08;

        xlabel( ...
            ax, ...
            'Current speed (m/s)', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 17, ...
            'Color', 'k');

        if b == 1
            ylabel( ...
                ax, ...
                'PSD Difference (dB)', ...
                'FontName', 'Times New Roman', ...
                'FontSize', 17, ...
                'Color', 'k');
        else
            set(ax, 'YTickLabel', []);
        end

        if strcmp(comp, 'BHZ') && b == 1

            h1 = plot( ...
                ax, ...
                nan, ...
                nan, ...
                'o-', ...
                'Color', col_flood, ...
                'MarkerFaceColor', col_flood, ...
                'MarkerEdgeColor', 'k', ...
                'MarkerSize', 4.5, ...
                'LineWidth', line_width);

            h2 = plot( ...
                ax, ...
                nan, ...
                nan, ...
                'o-', ...
                'Color', col_ebb, ...
                'MarkerFaceColor', col_ebb, ...
                'MarkerEdgeColor', 'k', ...
                'MarkerSize', 4.5, ...
                'LineWidth', line_width);

            legend( ...
                ax, ...
                [h1 h2], ...
                {'PSDdiff in Flood', 'PSDdiff in Ebb'}, ...
                'Location', 'northeast', ...
                'Box', 'off', ...
                'FontName', 'Times New Roman', ...
                'FontSize', 14);
        end
    end

    %% 8.5 Save Figure 4

    out_tif = fullfile( ...
        rd4Out, ...
        sprintf('Figure4_%s.tiff', comp));

    exportgraphics( ...
        Fig, ...
        out_tif, ...
        'Resolution', 300);

    close(Fig);

    %% 8.6 Save plotted statistics

    out_mat = fullfile( ...
        rd4Out, ...
        sprintf( ...
        'Figure4_PSDDiff_vs_Current_%s_%s_%s.mat', ...
        comp, st, et));

    save( ...
        out_mat, ...
        'PSD_time', ...
        'PSD_freq', ...
        'Speed_psd', ...
        'isFlood', ...
        'isEbb', ...
        'Bands', ...
        'Stats', ...
        'speed_edges', ...
        'speed_centers', ...
        'speed_bin_width', ...
        'minN');

    fprintf('Saved:\n  %s\n  %s\n', out_tif, out_mat);
end

disp('Finished.');

%% =========================================================================
% Local functions
% =========================================================================

function [StartTime, EndTime] = read_tidal_events(eventFile)
% Read a tab-delimited tidal-stage event file.
%
% Expected columns:
%   1. Event identifier or label
%   2. Start time: yyyy-MM-dd HH:mm:ss
%   3. End time:   yyyy-MM-dd HH:mm:ss

opts = detectImportOptions( ...
    eventFile, ...
    'Delimiter', '\t');

opts.VariableTypes = {
    'string'
    'datetime'
    'datetime'
};

opts = setvaropts( ...
    opts, ...
    2, ...
    'InputFormat', 'yyyy-MM-dd HH:mm:ss');

opts = setvaropts( ...
    opts, ...
    3, ...
    'InputFormat', 'yyyy-MM-dd HH:mm:ss');

Tab = readtable(eventFile, opts);

StartTime = datenum(Tab{:, 2});
EndTime   = datenum(Tab{:, 3});
end

function mask = in_periods(T, StartTime, EndTime)
% Check whether each time belongs to one or more event periods.

mask = false(size(T));

for i = 1:length(StartTime)
    mask = mask | ...
        (T >= StartTime(i) & T < EndTime(i));
end
end

function [x, y] = extract_freqtime_samples( ...
    PSD_freq, PSDdiff, Speed, idxStage, f1, f2)
% Extract all frequency-time PSDdiff samples in one frequency band and
% duplicate the matched current speed across frequency rows.

fidx = PSD_freq >= f1 & PSD_freq <= f2;

if ~any(fidx)
    x = [];
    y = [];
    return
end

tidx = idxStage & ~isnan(Speed);

if ~any(tidx)
    x = [];
    y = [];
    return
end

D = PSDdiff(fidx, tidx);
S = Speed(tidx);

S_mat = repmat( ...
    S(:).', ...
    size(D, 1), ...
    1);

x = S_mat(:);
y = D(:);

valid = ~isnan(x) & ~isnan(y);

x = x(valid);
y = y(valid);
end

function [xPlot, yPlot] = thin_points(x, y, maxN)
% Randomly thin scatter points for display.
% Retained from the original script although not currently called.

n = numel(x);

if n <= maxN
    xPlot = x;
    yPlot = y;
    return
end

rng(1);
idx = randperm(n, maxN);

xPlot = x(idx);
yPlot = y(idx);
end

function Stat = plot_binned_median_iqr_xy( ...
    ax, X, Y, edges, color_rgb, minN, line_width, shade_alpha)
% Calculate and plot the median and interquartile range in current-speed
% bins.

hold(ax, 'on');

nB = length(edges) - 1;

xc   = nan(1, nB);
medv = nan(1, nB);
q1v  = nan(1, nB);
q3v  = nan(1, nB);
nv   = zeros(1, nB);

for i = 1:nB

    idb = ...
        X >= edges(i) & ...
        X < edges(i + 1) & ...
        ~isnan(X) & ...
        ~isnan(Y);

    nv(i) = sum(idb);

    if nv(i) < minN
        continue
    end

    vals = Y(idb);

    xc(i) = ...
        (edges(i) + edges(i + 1)) / 2;

    medv(i) = median( ...
        vals, ...
        'omitnan');

    q1v(i) = prctile( ...
        vals, ...
        25);

    q3v(i) = prctile( ...
        vals, ...
        75);
end

valid = ~isnan(xc) & ~isnan(medv);

Stat.xc     = xc;
Stat.median = medv;
Stat.q1     = q1v;
Stat.q3     = q3v;
Stat.N      = nv;

if sum(valid) < 2
    return
end

x   = xc(valid);
med = medv(valid);
q1  = q1v(valid);
q3  = q3v(valid);

patch( ...
    ax, ...
    [x fliplr(x)], ...
    [q1 fliplr(q3)], ...
    color_rgb, ...
    'FaceAlpha', shade_alpha, ...
    'EdgeColor', 'none', ...
    'HandleVisibility', 'off');

plot( ...
    ax, ...
    x, ...
    med, ...
    '-', ...
    'Color', color_rgb, ...
    'LineWidth', line_width, ...
    'HandleVisibility', 'off');

plot( ...
    ax, ...
    x, ...
    med, ...
    'o', ...
    'MarkerFaceColor', color_rgb, ...
    'MarkerEdgeColor', 'k', ...
    'MarkerSize', 4.2, ...
    'LineWidth', 0.5, ...
    'HandleVisibility', 'off');
end
