%% MyPSD_main.m
% =========================================================================
% Calculate hourly amplitude spectra (SPE) and power spectral densities (PSD) from hourly SAC waveform segments.
%
% The numerical workflow is retained:
%   1. Loop through each day;
%   2. Loop through stations and components;
%   3. Read 24 hourly SAC acceleration files for each day;
%   4. Calculate the one-sided FFT amplitude spectrum;
%   5. Smooth the amplitude spectrum using kosmooth;
%   6. Interpolate to a logarithmically spaced frequency vector;
%   7. Convert the amplitude spectrum to PSD using the original formula;
%   8. Save daily SPE and PSD matrices.
%
% IMPORTANT INPUT REQUIREMENT
% ---------------------------
% The input SAC files must already:
%   - be divided into one-hour waveform segments;
%   - have the instrument response removed;
%   - be converted to acceleration;
%   - the PSD of time series a(t) is expressed as: Pk = 2*dt/N *|SPE|^2
%   - SPE is the spectra(S) after Fourier transform
%   - N is the number of samples in each time segment, dt=1/SR,N=WL*SR
%   - The unit of PSD is 1 m^2/s^4/Hz
%
% Expected hourly-SAC directory structure:
%
% Hourly_Seismic_acceleration_v1.0/
% └── YYYYMM/
%     └── YYYYMMDD/
%         └── STATION/
%             └── STATION.COMPONENT/
%                 ├── hour_00.SAC
%                 ├── hour_01.SAC
%                 ├── ...
%                 └── hour_23.SAC
%
% The filenames inside each component directory must sort chronologically
% with sort_nat.m, because the original workflow selects files by hour index.
%
% Required external functions:
%   rdSac.m
%   kosmooth.m
%   sort_nat.m
%
% Optional external functions retained from the original workflow:
%   TFsurfaceDF.m
%   TFPDF.m
%   MyPSD_avePSD.m
%
% If the optional functions are not present, SPE and PSD calculation and
% saving still proceed, while the corresponding optional step is skipped.
%
% Reference:
% McNamara, D. E., & Buland, R. P. (2004). Ambient noise levels in the continental United States.
% Bulletin of the Seismological Society of America, 94(4), 1517–1527. https://doi.org/10.1785/012003001
% =========================================================================

clc;
clear;
close all;

%% 1. Relative paths
% MyPSD_main.m is assumed to be located in:
%   ESS_OBS_Shield_Scripts_v1.0/
%
% The data and script repositories are assumed to be adjacent:
%   Research/
%   ├── ESS_OBS_Shield_Data_v1.0/
%   └── ESS_OBS_Shield_Scripts_v1.0/

script_file = mfilename('fullpath');
if isempty(script_file)
    error(['MATLAB cannot determine the location of MyPSD_main.m. ', ...
           'Run the saved script file rather than an unsaved editor buffer.']);
end

script_root  = fileparts(script_file);
project_root = fileparts(script_root);

% -------------------------------------------------------------------------
% USER CONFIGURATION:
% Set only this relative directory if the hourly SAC folder has a different
% name. Do not use an absolute path.
% -------------------------------------------------------------------------
hourly_sac_relative_dir = fullfile( ...
    'ESS_OBS_Shield_Data_v1.0', ...
    'Hourly_Seismic_acceleration_v1.0');

rd4SAC = fullfile(project_root, hourly_sac_relative_dir);

% Results generated by this script are written inside the script repository.
rd4PSD = fullfile(script_root, 'outputs', 'PSD');

if ~isfolder(rd4SAC)
    error(['Hourly SAC input directory not found:\n%s\n\n', ...
           'Expected data organization:\n', ...
           'YYYYMM/YYYYMMDD/STATION/STATION.COMPONENT/hourly SAC files'], ...
           rd4SAC);
end

if ~exist(rd4PSD, 'dir')
    mkdir(rd4PSD);
end

% Make local helper functions available.
addpath(script_root);

%% 2. PSD parameters
% These parameters retain the original calculation settings.
fbl = 0.01;
fbh = 10;
nof = 400;
WL  = 3600;
SR  = 100;

network = 'ZS';

% Components used for the T01/T02 OBS records.
Comp = ["BHE"; "BHN"; "BHZ"];

% Stations used in the manuscript analysis.
station = ["T01", "T02"];

% Primary analysis period.
st_datetime = datetime('20250314', 'InputFormat', 'yyyyMMdd');
et_datetime = datetime('20250331', 'InputFormat', 'yyyyMMdd');

%% 3. Verify required dependencies
required_functions = {'rdSac', 'kosmooth', 'sort_nat'};

for i_function = 1:numel(required_functions)
    function_name = required_functions{i_function};

    if exist(function_name, 'file') ~= 2
        error('Required function is missing from the MATLAB path: %s.m', ...
              function_name);
    end
end

%% 4. Daily processing
days_all = st_datetime:days(1):et_datetime;
Days = cellstr(datestr(days_all, 'yyyymmdd'));

for d = 1:numel(Days)

    day = Days{d};
    st = strcat(day, '000000');
    et = strcat(day, '240000');

    fprintf('\n============================================================\n');
    fprintf('Processing date: %s UTC\n', day);
    fprintf('============================================================\n');

    for i = 1:numel(station)

        sta = char(station(i));

        for j = 1:numel(Comp)

            component = char(Comp(j));

            fprintf('\nStation: %s | Component: %s\n', sta, component);

            [fc, SPE, PSD] = calculate_SPE_and_PSD( ...
                rd4SAC, ...
                rd4PSD, ...
                network, ...
                sta, ...
                component, ...
                st, ...
                et, ...
                SR, ...
                fbl, ...
                fbh, ...
                nof, ...
                WL); %#ok<ASGLU>
        end

        % Retain the original station-level postprocessing call when the
        % external function is available.
        if exist('MyPSD_avePSD', 'file') == 2
            MyPSD_avePSD(rd4PSD, network, sta, st, et);
        else
            warning(['Optional function MyPSD_avePSD.m was not found. ', ...
                     'Station-level averaging/postprocessing was skipped ', ...
                     'for %s on %s.'], sta, day);
        end
    end

    close all;
end

fprintf('\nPSD processing completed.\n');
fprintf('Output directory: %s\n', rd4PSD);

%% =========================================================================
% Local function: calculate SPE and PSD
% =========================================================================
function [fc, SPE, PSD] = calculate_SPE_and_PSD( ...
    rd4SAC, rd4PSD, network, station, Comp, ...
    st, et, SR, fbl, fbh, nof, WL)
% calculate_SPE_and_PSD
%
% The scientific calculation is unchanged:
%   - read hourly SAC acceleration data;
%   - calculate one-sided FFT amplitude;
%   - smooth using kosmooth;
%   - interpolate onto a logarithmic frequency vector;
%   - calculate PSD using:
%
%     PSD = 10*log10(SPE.^2 * 2/(SR^2*WL))
%
% Inputs:
%   rd4SAC  Root directory of hourly SAC files
%   rd4PSD  Root directory for generated SPE/PSD products
%   network Network code retained for compatibility
%   station Station name
%   Comp    Channel/component
%   st      Start time, YYYYMMDDHHMMSS
%   et      End time, YYYYMMDDHHMMSS
%   SR      Sampling rate in Hz
%   fbl     Lower frequency limit in Hz
%   fbh     Upper frequency limit in Hz
%   nof     Number of logarithmically spaced frequencies
%   WL      Window length in seconds
%
% Outputs:
%   fc      Logarithmically spaced frequency vector
%   SPE     SPE matrix
%   PSD     PSD matrix
%
% Matrix structure:
%   First row, columns 2:end: time
%   First column, rows 2:end: frequency
%   Matrix body: SPE or PSD values

if nargin < 11 || isempty(nof)
    nof = 400;
end

%% A. Format start and end times
YYYYs = str2double(st(1:4));
Mos   = str2double(st(5:6));
DDs   = str2double(st(7:8));
HHs   = str2double(st(9:10));
Mms   = str2double(st(11:12));
SSs   = str2double(st(13:14));

YYYYe = str2double(et(1:4));
Moe   = str2double(et(5:6));
DDe   = str2double(et(7:8));
HHe   = str2double(et(9:10));
Mme   = str2double(et(11:12));
SSe   = str2double(et(13:14));

dns = datenum([YYYYs, Mos, DDs, HHs, Mms, SSs]);
dne = datenum([YYYYe, Moe, DDe, HHe, Mme, SSe]);

% Calculate the time range in hours.
timerange = ceil(24 * (dne - dns));

spec = NaN(nof, timerange);

fcl = linspace(log10(fbl), log10(fbh), nof);
fc = NaN(nof, 1);

for i = 1:length(fcl)
    fc(i, 1) = 10^fcl(i);
end

T = NaN(1, timerange);

%% B. Read hourly SAC files and calculate SPE
flag = 0;

for ti = 1:timerange

    datef = datestr(dns + (ti - 1) / 24, 'yyyymmddTHHMMSS');

    T(1, ti) = datenum( ...
        str2double(datef(1:4)), ...
        str2double(datef(5:6)), ...
        str2double(datef(7:8)), ...
        str2double(datef(10:11)), ...
        0, ...
        0);

    % Retain the original hourly SAC directory organization.
    fol = fullfile( ...
        rd4SAC, ...
        datef(1:6), ...
        datef(1:8), ...
        station, ...
        strcat(station, '.', Comp));

    if ~isfolder(fol)
        error('Hourly SAC directory not found: %s', fol);
    end

    fnSP_A = dir(fol);
    files_name = sort_nat({fnSP_A.name});

    % Retain the original removal of "." and ".." directory entries.
    files_name(1:2) = [];

    files_folder = {fnSP_A.folder};
    files_folder(1:2) = [];

    if numel(files_name) < 24
        error(['Expected at least 24 hourly SAC files in:\n%s\n', ...
               'Found only %d files.'], fol, numel(files_name));
    end

    ti_original = ti;

    if ti > 24
        k = floor(ti / 24);
        ti = mod(ti, 24);

        if ti == 0
            ti = 24;
            k = k - 1;
        end

        flag = 1;
    end

    % Hourly SAC input, preserving the original file-selection logic.
    sac_file = fullfile(files_folder{ti}, files_name{ti});
    fprintf('Reading: %s\n', sac_file);

    [data, ~] = rdSac(sac_file);

    % Input SAC data have already been converted to acceleration.
    acceleration = data;

    npts = length(acceleration);
    nextpower = nextpow2(npts);
    NFFT = 2^nextpower;

    spet = fft(acceleration, NFFT);
    spe = spet(1:NFFT / 2 + 1);
    SPAM = abs(spe);

    % Frequency composition retained from the original workflow.
    F = linspace(0, 1, size(SPAM, 1)) * SR / 2;

    if flag == 1
        ti = ti + k * 24;
        flag = 0;
    end

    [Fs, smoothed_SPAM] = kosmooth( ...
        F, SPAM, [], fbl, fbh, nof);

    spec(:, ti) = interp1( ...
        Fs, smoothed_SPAM, fc, 'linear', 'extrap');

    % Restore loop variable value for clarity.
    ti = ti_original; %#ok<NASGU>
end

%% C. Assemble and save SPE matrix
SPE = NaN(nof + 1, timerange + 1);
SPE(1, 2:timerange + 1) = T;
SPE(2:nof + 1, 1) = fc;
SPE(2:nof + 1, 2:timerange + 1) = spec;

rd4data = fullfile(rd4PSD, 'data');

if ~exist(rd4data, 'dir')
    mkdir(rd4data);
end

spe_name = sprintf( ...
    'SPE_%s_%s_%s_%s', ...
    station, Comp, st(1:8), et(1:8));

spe_file = fullfile(rd4data, spe_name);

save(spe_file, 'SPE', '-ascii', '-double');

%% D. Calculate PSD from SPE
T_psd = SPE(1, 2:end);
F_psd = SPE(2:end, 1);
S_psd = SPE(2:end, 2:end);

PSDdata = NaN(length(F_psd), length(T_psd));

for i = 1:length(T_psd)
    for j = 1:length(F_psd)
        PSDdata(j, i) = 10 * log10( ...
            S_psd(j, i)^2 * (2 / (SR^2 * WL)));
    end
end

%% E. Assemble and save PSD matrix
PSD = NaN(size(PSDdata, 1) + 1, size(PSDdata, 2) + 1);
PSD(1, 2:size(PSDdata, 2) + 1) = T_psd;
PSD(2:size(PSDdata, 1) + 1, 1) = F_psd;
PSD(2:size(PSDdata, 1) + 1, 2:size(PSDdata, 2) + 1) = PSDdata;

psd_name = sprintf( ...
    'PSD_%s_%s_%s_%s.PSD', ...
    station, Comp, st(1:8), et(1:8));

psd_file = fullfile(rd4data, psd_name);

save(psd_file, 'PSD', '-ascii');

fprintf('Saved SPE: %s\n', spe_file);
fprintf('Saved PSD: %s\n', psd_file);

%% F. Optional PSD time-frequency plot retained from original workflow
if exist('TFsurfaceDF', 'file') == 2

    Fig1 = TFsurfaceDF(PSD, 1);
    set(Fig1, 'Visible', 'off');
    set(Fig1, 'Units', 'Inches');

    pos = get(Fig1, 'Position');

    set(Fig1, ...
        'PaperPositionMode', 'Auto', ...
        'PaperUnits', 'Inches', ...
        'PaperSize', [pos(3), pos(4)]);

    rd4PSDDF = fullfile(rd4PSD, 'PSDDF', station);

    if ~exist(rd4PSDDF, 'dir')
        mkdir(rd4PSDDF);
    end

    psd_figure_file = fullfile( ...
        rd4PSDDF, ...
        sprintf('PSDDF_%s_%s_%s_%s.png', ...
        station, Comp, st(1:8), et(1:8)));

    saveas(Fig1, psd_figure_file);
    close(Fig1);

else
    warning(['Optional function TFsurfaceDF.m was not found. ', ...
             'PSD time-frequency plotting was skipped.']);
end

%% G. Optional PDF calculation retained from original workflow
if exist('TFPDF', 'file') == 2

    rd4PDF = fullfile(rd4PSD, 'PDF', station);

    if ~exist(rd4PDF, 'dir')
        mkdir(rd4PDF);
    end

    TFPDF(PSD, station, Comp, st, et, rd4PDF);

else
    warning(['Optional function TFPDF.m was not found. ', ...
             'PSD probability-density calculation was skipped.']);
end

end
